### ISSUE TITLE
How you pass app registration in FB?

### ISSUE THREAD

**Issue by OleksandrKucherenko** [ashwin47/Net-Neutral#2] opened 2016-02-01 23:33 UTC
%subj%

**Comment by rhnvrm** [comment] 2016-02-02 18:49
@OleksandrKucherenko are you asking about the App ID and App Secret? If yes, see this from the readme.

> Please add a file named cred.php to the folder and add the following lines in them:
> 
> ```
> <?php
> $_YOUR_APP_ID = 'XYZ';
> $_YOUR_APP_SECRET = 'XYZ';
> ?>
> ```

**Comment by meedz** [comment] 2016-02-07 03:53
Showing 'sorry this page is not found' from facebook..when i login

**Comment by rhnvrm** [comment] 2016-02-07 06:28
Did you add the proper call back? if you are using on local host please use it as the callback

**Comment by ashwin47** [comment] 2016-02-07 07:12
The problem is callback url which should be project specific.
resolving it.

**Comment by ashwin47** [comment] 2016-02-07 07:45
Pushed fix please verify.

**Comment by meedz** [comment] 2016-02-08 15:54
Guys Fixed the Problem Thank you

**Closed as completed** 2016-02-09 06:39 UTC
